### ISSUE TITLE
ProviderElementBase.read: Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by JonasTeich** [otakoyi/flutter_ddd_riverpod_example#5]
I get this error when clicking on the sign in with google button:

```
E/flutter ( 9002): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 9002): #1      ProviderElementBase.read (package:riverpod/src/framework/element.dart:689:23)
E/flutter ( 9002): #2      SignInWithGoogleController.signInWithGoogle (package:example/features/auth/application/sign_in_with_google_controller.dart:17:27)
E/flutter ( 9002): #3      SignInWithGoogleButton.build.<anonymous closure> (package:example/features/auth/presentation/widgets/sign_in_with_google_button.dart:18:65)
E/flutter ( 9002): #4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
E/flutter ( 9002): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
E/flutter ( 9002): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
E/flutter ( 9002): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
E/flutter ( 9002): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
E/flutter ( 9002): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
E/flutter ( 9002): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
E/flutter ( 9002): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
E/flutter ( 9002): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
E/flutter ( 9002): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
E/flutter ( 9002): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
E/flutter ( 9002): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
E/flutter ( 9002): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
E/flutter ( 9002): #17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439:11)
E/flutter ( 9002): #18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
E/flutter ( 9002): #19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
E/flutter ( 9002): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
E/flutter ( 9002): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
E/flutter ( 9002): #22     _invoke1 (dart:ui/hooks.dart:328:13)
E/flutter ( 9002): #23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410:7)
E/flutter ( 9002): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
E/flutter ( 9002): #25     ProviderElementBase.watch (package:riverpod/src/framework/element.dart:739:20)
E/flutter ( 9002): #26     authRepository (package:example/features/auth/auth_provider.dart:14:26)
E/flutter ( 9002): #27     ProviderElementBase.read (package:riverpod/src/framework/element.dart:688:12)
E/flutter ( 9002): #28     SignInWithGoogleController.signInWithGoogle (package:example/features/auth/application/sign_in_with_google_controller.dart:17:27)
E/flutter ( 9002): #29     SignInWithGoogleButton.build.<anonymous closure> (package:example/features/auth/presentation/widgets/sign_in_with_google_button.dart:18:65)
 ```

**Comment by JonasTeich** [comment]
I noticed that supabase is initialised twice. Thats why there is an error inside the `authControllerProvider` and the `authRepositoryProvider` does not work.

**Comment by eugenemartseniuk** [comment]
Hi @JonasTeich. Make sure you have an actual supabase project and you environment config file includes it

**Comment by JonasTeich** [comment]
That's already the case. The first initialization of supabase works fine, but then the initialization is triggered again.

**Comment by JonasTeich** [comment]
This is the log I get:
```
flutter:       {
flutter:       "provider": "sharedPreferencesProvider",
flutter:       "newValue": "AsyncData<SharedPreferences>(value: Instance of 'SharedPreferences')"
flutter:       }
flutter: ***** Supabase init completed Instance of 'Supabase'
flutter: ***** SupabaseDeepLinkingMixin startAuthObserver
flutter: **** onAuthStateChange: AuthChangeEvent.initialSession
flutter:       {
flutter:       "provider": "authControllerProvider",
flutter:       "newValue": "AsyncError<UserEntity?>(error: Null check operator used on a null value, stackTrace: #1      ProviderElementBase.watch (package:riverpod/src/framework/element.dart:741:20)
flutter: #2      AuthController.build (package:example/features/auth/application/auth_controller.dart:14:28)
flutter: #3      ProviderContainer.read (package:riverpod/src/framework/container.dart:241:21)
flutter: #4      initializeProviders (package:example/config/providers.dart:61:13)
flutter: #5      bootstrap (package:example/bootstrap.dart:14:3)
flutter: #6      main (package:example/main_local.dart:11:18)
flutter: #7      ProviderElementBase.watch (package:riverpod/src/framework/element.dart:741:20)
flutter: #8      authRepository (package:example/features/auth/auth_provider.dart:14:26)
flutter: #9      ProviderElementBase.watch (package:riverpod/src/framework/element.dart:713:12)
flutter: #10     AuthController.build (package:example/features/auth/application/auth_controller.dart:14:28)
flutter: #11     ProviderContainer.read (package:riverpod/src/framework/container.dart:241:21)
flutter: #12     initializeProviders (package:example/config/providers.dart:61:13)
flutter: #13     bootstrap (package:example/bootstrap.dart:14:3)
flutter: #14     main (package:example/main_local.dart:11:18)
flutter: #15     supabaseClient (package:example/config/providers.dart:42:49)
flutter: #16     ProviderElementBase.watch (package:riverpod/src/framework/element.dart:713:12)
flutter: #17     authRepository (package:example/features/auth/auth_provider.dart:14:26)
flutter: #18     ProviderElementBase.watch (package:riverpod/src/framework/element.dart:713:12)
flutter: #19     AuthController.build (package:example/features/auth/application/auth_controller.dart:14:28)
flutter: #20     ProviderContainer.read (package:riverpod/src/framework/container.dart:241:21)
flutter: #21     initializeProviders (package:example/config/providers.dart:61:13)
flutter: )"
flutter:       }
flutter:       {
flutter:       "provider": "supabaseProvider",
flutter:       "newValue": "AsyncError<Supabase>(error: 'package:supabase_flutter/src/supabase.dart': Failed assertion: line 81 pos 7: '!_instance._initialized': This instance is already initialized, stackTrace: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
flutter: #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
flutter: #2      Supabase.initialize (package:supabase_flutter/src/supabase.dart:81:7)
flutter: #3      supabase (package:example/config/providers.dart:32:19)
flutter: <asynchronous suspension>
flutter: #4      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348:9)
flutter: <asynchronous suspension>
flutter: )"
flutter:       }
flutter:       {
flutter:       "provider": "supabaseClientProvider",
flutter:       "newValue": "null"
flutter:       }
flutter:       {
flutter:       "provider": "authRepositoryProvider",
flutter:       "newValue": "null"
flutter:       }

```

**Comment by JonasTeich** [comment]
Alright, the initialisation problem is fixed. Thank you.

But I still have a problem with the `authRepositoryProvider`. In `sign_in_with_google_controller.dart` on line 17 the `ref.read(authRepositoryProvider)` call doesn't work. It will throw the Error mentioned in the initial Issue.

Is there something wrong with the `SignInWithGoogleController`? I can read the `authRepositoryProvider` from different places without any problem.

**Comment by eugenemartseniuk** [comment]
I think that error is because this code works with old Google auth implementation for Firebase and since couple of months back the requirements changed. I need to fix this, but I don't have time at the moment. Please look at the snippets above and additionally look into Supabase docs.

If you are using this in Flutter web, you need to use google_sign_in package and renderButton() method to get the button, and you need to listen to google auth stream separately to get the ID token and feed it to Supabase. I am not closing this issue, since it's a reminder I need to get my hands on it

**Comment by JonasTeich** [comment]
This Issue doesn't have anything to do with the Google Auth Implementation. This error also occurs when I replace the google Auth stuff with a log or something. 

When I call `ref.read(authControllerProvider)` in the signInWithGoogle Method of the SignInWithGoogleController, I get the Error: `Unhandled Exception: Null check operator used on a null value`.

However when I do `container.read(authControllerProvider)` in the bootstrap Method, the error doesn't occur.

'm sorry to bother you. But I simply can't understand what my problem is. 😅

When you try to run the app as it is on main right now, will it work for you?

**Comment by ghost** [comment]
I think you mean authRepositoryProvider?
I think I found the issue - line 15 in auth_provider.dart. It was to do with shared prefs initilizations. I pushed the fix. Make sure you re-run the build_runner after you pull changes and let me know if it worked

**Comment by jonasteich** [comment]
Nice, it worked! Thank you very much!
